# general settings
name: 019_train_SwinIR+SynFacDensePos_Fix0_SRx4_P48W8_DF2K_500k_B8G1
model_type: SwinIRModel
scale: 4
num_gpu: auto
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: datasets/DF2K/DF2K_train_HR_sub.lmdb
    dataroot_lq: datasets/DF2K/DF2K_train_LR_bicubic_X4_sub.lmdb
    # meta_info_file: basicsr/data/meta_info/meta_info_DIV2K800sub_GT.txt
    filename_tmpl: '{}'
    io_backend:
      #type: disk
      type: lmdb

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Set5/GTmod12
    dataroot_lq: datasets/Set5/LRbicx4
    io_backend:
      type: disk

  val_1:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/Set14/GTmod12
    dataroot_lq: datasets/Set14/LRbicx4
    io_backend:
      type: disk

  val_2: # the 2nd test dataset
    name: B100
    type: PairedImageDataset
    dataroot_gt: datasets/B100/HR
    dataroot_lq: datasets/B100/LR_bicubic/X4
    io_backend:
      type: disk


  val_3: # the 2nd test dataset
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: datasets/Urban100/HR
    dataroot_lq: datasets/Urban100/LR_bicubic/X4
    io_backend:
      type: disk
      
  val_4: # the 3nd test dataset
    name: Manga109
    type: PairedImageDataset
    dataroot_gt: datasets/Manga109/original/
    dataroot_lq: datasets/Manga109/LRbicx4/
    io_backend:
      type: disk
      
  val_5: # the 2nd test dataset
    name: DIV2K_valid
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_valid_HR/
    dataroot_lq: datasets/DIV2K/DIV2K_valid_LR_bicubic/X4/
    io_backend:
      type: disk



# network structures
network_g:
  type: SynSwinIR_Fix0
  upscale: 4
  in_chans: 3
  img_size: 48
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6]
  embed_dim: 60
  num_heads: [6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
  attn_type: 'fact_dense_pose'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true

    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    #project: Efficient_Transformer
    project: ~
    resume_id: ~
    #entity: x-pixel-2022-summer

# dist training settings
dist_params:
  backend: nccl
  port: 29500
